# the first step is always the same: import all necessary components:

import smtplib

from socket import gaierror

# now you can play with your code. Let’s define the SMTP server separately here:

port = 25

smtp_server = "mail.ditchflow.com"

login = "alert@ditchflow.com"  # paste your login generated by Mailtrap

password = "SINCE1937"  # paste your password generated by Mailtrap

# specify the sender’s and receiver’s email addresses

sender = "alert@ditchflow.com"

receiver = "petras.moil@gmail.com"

# type your message: use two newlines (\n) to separate the subject from the message body, and use 'f' to  automatically insert variables in the text

message = f"""\

Subject: test of ditchflow

To: {receiver}

From: {sender}



Sensor 1 battery is low."""

try:

    # send your message with credentials specified above

    with smtplib.SMTP(smtp_server, port) as server:

        server.login(login, password)

        server.sendmail(sender, receiver, message)

    # tell the script to report if your message was sent or which errors need to be fixed

    print('Sent')

except (gaierror, ConnectionRefusedError):

    print('Failed to connect to the server. Bad connection settings?')

except smtplib.SMTPServerDisconnected:

    print('Failed to connect to the server. Wrong user/password?')

except smtplib.SMTPException as e:

    print('SMTP error occurred: ' + str(e))
