"""add config table

Revision ID: 3c6b032aed48
Revises: f29c1b235df6
Create Date: 2020-11-25 18:58:54.419360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6b032aed48'
down_revision = 'f29c1b235df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'active')
    # ### end Alembic commands ###
