"""empty message

Revision ID: 4ea38ad27588
Revises: 8302a6f9c0d8
Create Date: 2020-10-22 17:07:48.076261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea38ad27588'
down_revision = '8302a6f9c0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('autorun', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set', 'autorun')
    # ### end Alembic commands ###
