"""Add proflow and run to Valve table

Revision ID: a2772f0d4b71
Revises: d793ffd20d02
Create Date: 2020-10-17 17:32:06.034203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2772f0d4b71'
down_revision = 'd793ffd20d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valve', sa.Column('preflow', sa.Integer(), nullable=True))
    op.add_column('valve', sa.Column('run', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valve', 'run')
    op.drop_column('valve', 'preflow')
    # ### end Alembic commands ###
