"""empty message

Revision ID: f29c1b235df6
Revises: 4ea38ad27588
Create Date: 2020-11-13 19:48:33.335442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29c1b235df6'
down_revision = '4ea38ad27588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('autorun', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set', 'autorun')
    # ### end Alembic commands ###
